### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by mertyildiran** [junku901/machine_learning#6]
I installed via **npm**: `npm install machine_learning`

When I try to run *Logistic Regression* example with `nodejs logis.js` I'm getting this error:

```
/home/mertyildiran/Documents/npm/machine_learning/node_modules/machine_learning/lib/machine_learning.js:4
let ml = module.exports;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mertyildiran/Documents/npm/machine_learning/logis.js:1:72)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by junku901** [comment]
Thank you for noticing me the problem. I update the package in npm.

**Comment by EnKrypt** [comment]
Hey, this issue is not yet solved. Any updates?

**Comment by wollardj** [comment]
Just submitted pull request #7 to address this issue.
